### ISSUE TITLE
Sidenotes not numbered correctly in pages

### ISSUE THREAD

**Issue by cryptogenomicon** [out-of-cheese-error/astrochelys#1]
Thanks for Astrochelys, it's very well done and I've learned a lot from studying it.

I think I found a small problem with the sidenote counter. It works fine for articles, but in a page, sidenote numbering resets at each new paragraph. I fixed this by adding a `<section id="content" class="body">` tag to `templates/page.html`, so it now reads like the analogous piece of code in `templates/article.html`, like this:

```
{% block content %}
<section id="content" class="body">
  <header><h1>{{ page.title }}</h1></header>
  {{ page.content }}

  {% if page.modified %}
  <p>Last updated: {{ page.locale_modified }}</p>
  {% endif %}
</section>
{% endblock %}
```

**Comment by Ninjani** [comment]
Glad you're finding it useful! Thanks for the issue, I didn't catch this since we haven't used sidenotes in pages yet. Made the fix now.
